# Generated by Django 3.2.2 on 2021-05-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=50)),
                ('nome_setor', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
