# Generated by Django 3.2.2 on 2021-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField(auto_now_add=True)),
                ('setor', models.CharField(max_length=30)),
                ('status_empresa', models.CharField(max_length=20)),
            ],
        ),
    ]
