# Generated by Django 3.2.2 on 2021-05-15 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 15, 15, 35, 6, 680182)),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
