# Generated by Django 3.2.2 on 2021-05-15 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20210515_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 15, 18, 33, 9, 634275)),
        ),
    ]
