# Generated by Django 3.2.2 on 2021-05-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_auto_20210515_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Protocolo',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
