# Generated by Django 3.2.2 on 2021-05-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 16, 8, 6, 59, 756653)),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
