# Generated by Django 3.2.2 on 2021-05-16 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_auto_20210516_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 16, 17, 19, 15, 201350)),
        ),
    ]
