# Generated by Django 3.2.2 on 2021-05-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0003_alter_protocolo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 16, 18, 30, 33, 780845)),
        ),
    ]
