# Generated by Django 3.2.2 on 2021-05-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=90)),
                ('cpf', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('status_empresa', models.CharField(max_length=20)),
                ('setor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='setor.setor')),
            ],
        ),
    ]
