# Generated by Django 3.2.2 on 2021-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': (('gerar_protocolos', 'user can create new protocol'),)},
        ),
    ]
