# Generated by Django 3.2.2 on 2021-05-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': (('gerar_protocolos', 'user can create new protocol'), ('rh_acess', 'Acessos de RH no sistema CRUD'))},
        ),
    ]
